# Generated by Django 6.0.6 on 2026-07-09 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='kra_pin',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nhif_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nssf_number',
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
